using System.Collections.Generic;
using System.Linq;

namespace Interceptus.Generator.CSharpWriter;

internal class CSharpFile : ICSharpUnit
{
    public List<string> Usings { get; set; } = [];
    public string Namespace { get; set; } = string.Empty;
    public List<CSharpClass> Classes { get; set; } = [];
    
    public new string ToString()
    {
        var usings = string.Join("\n", Usings.Select(x => $"using {x};"));
        var classes = string.Join("\n", Classes.Select(x => x.ToString()));

        return $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
{usings}

namespace {Namespace};

{classes}";

    }
}